spring:
  application.name: nvite
  thymeleaf.cache: false

  data:
    mongodb:
      uri: mongodb+srv://n-vite-app:oCz5Sz5urHaU3nk2@cluster0.or1qk.mongodb.net/account


springdoc.swagger-ui.path: /swagger-ui.html
springdoc.api-docs.path: /api-docs