#springdoc:
#  swagger-ui.enabled: true
#  api-docs.enabled: true

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: WARN
    org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration: WARN

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application.name: nvite
  thymeleaf.cache: false

  data:
    mongodb:
      uri: ${MONGO_URL_ENV}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID_ENV}
            client-secret: ${GOOGLE_CLIENT_SECRET_ENV}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


