package tech.nvite.domain;

public enum SectionType {
  DRESS_CODE,
  ACCOMMODATION,
  DAY_SCHEDULE,
  GIFT_REGISTRY,
  OUR_STORY,
  WEDDING_PARTY,
  FAQ,
  TRANSPORT,
  SONG_REQUEST,
  HONEYMOON_FUND,
  CHILDREN_POLICY,
  PARKING,
  COUNTDOWN,
  MENU_PREVIEW,
  PHOTO_GALLERY,
  COUPLE_QUOTE
}
